### ISSUE TITLE
[REQUEST] Please add environment variables

### ISSUE THREAD

**Issue by Kira-Pgr** [Lu1sDV/wafme0w#1]
After installing using command `go install -v github.com/Lu1sDV/wafme0w/cmd/wafme0w@latest`, environment variables won't be automatically added.   
so only running `cat list.txt | wafme0w --concurrency 30 --no-warning --no-generic` will give an error `wafme0w: command not found`

**Comment by gtrrnr** [comment]
It's most likely a problem with your go installation since you probably don't have GOROOT/GOPATH set in your shell environment.

Try installing it using this script:
https://github.com/canha/golang-tools-install-script/blob/master/goinstall.sh

Change https://github.com/canha/golang-tools-install-script/blob/master/goinstall.sh#L5 to 1.20 (or grab actual version at https://go.dev/dl/)
It should automatically build it from sources and set correct GOROOT/GOPATH.
